KeyBindEvents.modify(event => {
    // event.modifyKey('key.curios.open.desc', GLFM.GLFM_KEY_X)
    // event.modifyModifier('key.curios.open.desc', KeyModifier.ALT)
    KeyBindEvents.firstKeyPress()


    // event.modifyCategory('key.curios.open.desc', 'key.categories.misc')

    // event.remove('key.jujutsucraft.key_forward')
    // event.remove('key.jujutsucraft.key_change_technique')
    // event.remove('key.jujutsucraft.key_simple_domain')
    // event.remove('key.jujutsucraft.key_start_technique')
    // event.remove('key.jujutsucraft.key_reset_technique')
    // event.remove('key.jujutsucraft.key_reverse_cursed_technique')
    // event.remove('key.jujutsucraft.key_switch_cursed_technique')
    // event.remove('key.jujutsucraft.key_domain_amplification')
    // event.remove('key.jujutsucraft.key_backstep')
    // event.remove('key.jujutsucraft.key_space')
    event.remove('key.kimetsunoyaiba.check_back_step')
    event.remove('key.kimetsunoyaiba.key_special_attack')
    event.remove('key.kimetsunoyaiba.jump')
    event.remove('key.kimetsunoyaiba.key_demon_slayer_mark')
    // event.remove('key.kimetsunoyaiba.change_breathes_and_blood_art')
    // event.remove('key.minepiece.key_switch_technique')
    // event.remove('key.minepiece.key_backstep')
    // event.remove('key.minepiece.key_reset_technique')
    // event.remove('key.minepiece.key_haoshoku_haki')
    // event.remove('key.minepiece.key_for_orca')
    // event.remove('key.minepiece.key_start_technique')
    // event.remove('key.minepiece.key_change_technique')
    // event.remove('key.minepiece.key_transform')
    // event.remove('key.minepiece.key_forward')
    // event.remove('key.minepiece.key_space')
    // event.remove('key.minepiece.key_p')
    event.remove('key.paladins_oath.f_8')
    event.remove('key.paladins_oath.power_button_2')
    event.remove('key.paladins_oath.power_button_1')
    event.remove('key.paladins_oath.power_button_3')
    event.remove('key.chaos_project.blood_runner_ability')
    event.remove('key.chaos_project.dragonslayer_dash')
    event.remove('key.chaos_project.emberoted_set_bonus')
    event.remove('key.chaos_project.flesh_heal')
    event.remove('key.chaos_project.holy_spirit_spawn_armor')
    event.remove('key.chaos_project.mintolis_regenerative_gift')
    event.remove('key.chaos_project.moss_dash')
    event.remove('key.chaos_project.moss_down')
    event.remove('key.chaos_project.moss_up')
    event.remove('key.chaos_project.obsided_resistance')
    event.remove('key.chaos_project.pumpkin_set_eat')
    event.remove('key.chaos_project.tulicite_boost_set')
    event.remove('key.chaos_project.wither_set_dash')
    event.remove('key.greek_tales.amulet_ability')
    event.remove('key.greek_tales.ability_1')
    event.remove('key.greek_tales.ability_2')
    event.remove('key.greek_tales.ability_3')
})

KeyBindEvents.register((event) => {
  // 創建按鍵綁定 (第一個參數為標識，按鍵觸發都會使用這個標識)
  event.create("helmet_skill", "头盔技能", -1, "tales_of_element");
  event.create("chestplate_skill", "胸甲技能", -1, "tales_of_element");
  event.create("legging_skill", "护腿技能", -1, "tales_of_element");
  event.create("boots_skill", "鞋子技能", -1, "tales_of_element");
});