
[Season]
	#The lasting days of each term (24 in total).
	#Range: 1 ~ 30
	LastingDaysOfEachTerm = 7
	#The index of the initial solar term.
	#Range: 1 ~ 24
	InitialSolarTermIndex = 1
	#Enable solar term change inform.
	EnableInform = true

[Weather]
	#Enable solar term weather system with biome.
	UseSolarWeather = true
	#Set the percentage multiplier of the probability of rain, the range should be between 0 and 1000.
	#Range: 0 ~ 1000
	RainChancePercentMultiplier = 60
	#Set the percentage multiplier of the probability of thunder in the rain, the range should be between 0 and 1000.
	#Range: 0 ~ 1000
	ThunderChancePercentMultiplier = 80

[Temperature]
	#Ice or snow layer will melt in warm place..
	IceAndSnowMelt = false
	#Add heat stroke effect in summer noon while in hot biome.
	HeatStroke = true

[Crop]
	#Enable crop season control.
	EnableSeasonalCrop = true
	#How much chance can crop grow in wrong season.
	#Range: 0.0 ~ 1.0
	CropGrowChanceInWrongSeason = 0.25
	#Enable crop humidity control.
	EnableCropHumidityControl = true
	#If a crop is not registered for a season or humid type, default values will be used.
	UseDefaultValue = false

[Debug]
	#Enable debug option to detect illegal use of functions.
	Debug = false
	#Without snowy block under the light blocks which level is 0.
	NotSnowyUnderLight0 = false

[Compat]
	#Compatible with mods using SereneSeasons' CropTag.
	SereneSeasonsCropTag = true

