
["Number tweaks"]
	#When enchantment levels are uncapped by other mods,
	#what is the maximum enchantment cost that should be
	#used to scale this mod's overcapped levels.
	#An example is Apotheosis with their default max cost of 200.
	#This is to allow controlled overcap as opposed to uncontrolled.
	#Range: 31 ~ 1000
	overcap_max_cost = 199
	#Fortress's max health ratio per level in decimal form.
	#Range: 0.0 ~ 0.1
	fortress_max_health_ratio_per_level = 0.01
	#Control whether Fortress scales less effectively as max health increases.
	#Remember that Fortress applies to every instance of damage dealt,
	#not just melee.
	#When off, it is maxHP * fortress_max_health_ratio_growth * level.
	#When on, it is (maxHP + 20)/1.3 * fortress_max_health_ratio_growth * level,
	#or better at base vanilla health but scales a bit slower (still linear and infinite).
	fortress_scales_worse = true
	#Each pet provides this much attack damage with Commander enchantment.
	#Note that is an attribute modifier.
	#Range: 0.0 ~ 1.7976931348623157E308
	commander_bonus_damage_per_pet = 0.5
	#The max bonus damage provided by Commander,
	#to discourage having too many pets causing entity lag.
	#Range: 0.0 ~ 1.7976931348623157E308
	commander_max_bonus_damage = 5.0
	#Crime and Punishment deals this much damage per level.
	#Half of this is given based on their combined levels
	#and half is given based on their min level.
	#Range: 0.0 ~ 1.7976931348623157E308
	crime_punishment_bonus_damage_per_level = 2.0
	#The range to check for nearby pets.
	#Range: 1.0 ~ 64.0
	pet_query_range = 12.0
	#Controls whether Forbiden Syzygy applies Glowing to entities hit by arrows.
	forbidden_syzygy_applies_glowing = true
	#Controls whether Puzzle 4 effect applies Glowing to attacker.
	puzzle_4_applies_glowing = true
	#Puzzle 6 reduces damage taken by this much
	#multiplied by attacker's max health over victim's max health
	#in decimal form.
	#Range: 0.0 ~ 1.0
	puzzle_6_damage_reduction = 0.01
	#Puzzle 6 damage reduction reaches a cap of
	#this value, in decimal form.
	#Range: 0.0 ~ 1.0
	puzzle_6_damage_reduction_cap = 0.5
	#Firework rockets shot with Rocket Specialist deal
	#percentage increased damage, in decimal form.
	#Range: 0.0 ~ 1.7976931348623157E308
	rocket_specialist_bonus_damage_per_level = 0.25
	#Firework rockets shot with Rocket Specialist have
	#percentage increased explosion radius, in decimal form.
	#Range: 0.0 ~ 0.5
	rocket_specialist_bonus_radius_per_level = 0.15
	#Sancta Potentia causes arrows to deal this much extra flat damage.
	#Range: 0.0 ~ 1.7976931348623157E308
	sancta_potentia_bonus_flat_damage = 6.0
	#Mare Potentia causes arrows to deal this much
	#extra percentage damage, in decimal form,
	#eg 0.7 = 70% increased damage.
	#The intention was to make Sacred Corona and Shining Maria
	#worse than Power V individually, but stronger together.
	#They also have some defensive properties so they don't
	#need to always be stronger.
	#Range: 0.0 ~ 1.7976931348623157E308
	mare_potentia_bonus_percent_damage = 0.7
	#Puzzle 5's neutral and positive effects' duration
	#is multiplied by this value, in decimal form.
	#Range: 1.0 ~ 1.7976931348623157E308
	puzzle_5_effect_duration_extension = 1.5
	#Puzzle 5's neutral and positive effects' duration
	#is further multiplied by this value when drinking potions,
	#in decimal form.
	#Range: 1.0 ~ 1.7976931348623157E308
	puzzle_5_effect_duration_extension_potion = 1.33
	#Puzzle 5's negative effects' duration
	#is multiplied by this value, in decimal form.
	#Range: 0.0 ~ 1.0
	puzzle_5_effect_duration_reduction = 0.67
	#Thermoshock does this much damage per level.
	#Range: 0.0 ~ 1.7976931348623157E308
	thermoshock_bonus_damage_per_level = 6.0
	#Thermohex causes burn or freeze DOT to be increased by this much
	#based on victim's max health, in decimal form.
	#
	#Range: 0.0 ~ 1.0
	thermohex_max_health_ratio_base = 0.02
	#Each level of Thermohex increases the max health ratio by this much
	#in decimal form.
	#
	#Range: 0.0 ~ 1.0
	thermohex_max_health_ratio_per_level = 0.01

["Black/whitelist"]
	#List of effects whose duration should not be modified by Puzzle 5.
	puzzle_5_blacklist = ["irons_spellbooks:vex_timer", "irons_spellbooks:polar_bear_timer", "irons_spellbooks:raise_dead_timer", "irons_spellbooks:summon_horse_timer"]

