
["Configs for Shadowlands"]
	#Show warning about getting the mod from unsafe sites on first world load
	"Do first load message" = true
	#Give guide book on first world load
	"Do first load guide" = true

